server:
  port: 8190
  servlet:
    context-path: /tasks

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgres:5432/products
#    username: passportpguser
#    password: pgpwd4passport
#  flyway:
#    user: passportpguser
#    password: pgpwd4passport
#    url: jdbc:postgresql://postgres:5432/products
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

bot:
  token: *
  name: *


jira:
  url: *
  username: *
  password: *
  assignee: k.dzhigante
  projectKey: GISMTOPS
